### ISSUE TITLE
iges.to_vtk error

### ISSUE THREAD

**Issue by amscosta** [pyvista/pyiges#45]
The following error is displayed when I load the default example igs : 

lines = iges.to_vtk(bsplines=True, surfaces=False, merge=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\VMTK\lib\site-packages\pyiges\check_imports.py", line 21, in safe_func
    raise Exception(_PROBLEM_MSG)
Exception: Import from 'None' failed, to support this feature please install pyiges[full]

**Comment by amscosta** [comment]
I installed pyiges[full] twice, using both suggested methods.

**Comment by mikamove** [comment]
Thanks for Your feedback! Could You please post the output when using this method?

pip install pyiges[full]

**Comment by amscosta** [comment]
yes. Both methods

Em sáb., 3 de fev. de 2024 às 04:14, mikamove ***@***.***>
escreveu:

**Comment by mikamove** [comment]
The problem is most likely not in the IGES file, but in the installation itself. When You install *pyiges[full]* it should automatically install additional dependencies. Your error message indicates, that these dependencies are missing. 

Therefore I asked You if You could please post the output of the command "pip install pyiges[full]", I couldn't see this  in Your answer. Could You please provide it?
